name: Run Jest Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Database
        run: |
          pnpm prisma generate
          pnpm prisma migrate dev --name init
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"

      - name: Run Tests
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: pnpm test

